---
- name: Execute 'show interfaces' on Cisco devices
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Run 'show interfaces'
      cisco.ios.ios_command:
        commands:
          - show interfaces
      register: interfaces_output
      
    - name: Display output interfaces
      debug:
        var: interfaces_output.stdout_lines
