---
- name: Execute 'show policy-map' on Cisco devices
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Run 'show ip int brief'
      cisco.ios.ios_command:
        commands:
          - show ip int brief
      register: int_brief_output
    - name: Run 'policy map'
      cisco.ios.ios_command:
        commands:
          - policy_map_output
      register: show policy map
      
    - name: Display output policy map
      debug:
        var: policy_map_output.stdout_lines
    - name: Display output ip int brief
      debug:
        var: int_brief_output.stdout_lines
