---
- name: Check RouterOS Version
  connection: network_cli
  hosts: mikrotik
  gather_facts: False

  tasks:
    - name: Show RouterOS Version
      community.network.routeros_command:
        commands: system resource print
      register: result

    - name: Display RouterOS Version
      debug:
        msg: "{{ result.stdout }}"
