---
- name: Execute 'show policy-map' on Cisco devices
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Run 'show policy-map'
      cisco.ios.ios_command:
        commands:
          - show policy-map
      register: policy_map_output

    - name: Display output
      debug:
        var: policy_map_output.stdout_lines
